//! # Preset Management
//!
//! This module defines the structure of a DSP preset and provides an extensive
//! library of factory tones. Each preset contains parameters for the core engine
//! stages as well as a specific effects chain configuration.

use serde::{Deserialize, Serialize};

/// Represents a full engine state patch.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Preset {
    /// Distinctive name of the preset (e.g., "Back in Black").
    pub name: String,
    /// Broad category (e.g., "ROCK LEGENDS").
    pub category: String,
    /// A short description of the tone and intended use.
    pub description: String,
    /// Static parameters for the main engine stages.
    pub parameters: PresetParameters,
    /// Dynamic configuration for the modular effects chain.
    pub effects_chain: Vec<EffectConfig>,
}

/// Individual parameter values for a preset's engine stages.
/// All values are typically normalized between 0.0 and 1.0.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresetParameters {
    pub volume: f32,
    pub pan: f32,
    pub drive: f32,
    pub glide: f32,
    pub attack: f32,
    pub decay: f32,
    pub sustain: f32,
    pub release: f32,
    pub cutoff: f32,
    pub res: f32,
    pub env: f32,
    pub drive2: f32,
    pub rev_decay: f32,
    pub rev_size: f32,
    pub rev_mix: f32,
    pub dly_time: f32,
    pub dly_feed: f32,
    pub dly_mix: f32,
}

/// Configuration for a specific effect module within a preset.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EffectConfig {
    /// Name of the effect module.
    pub name: String,
    /// Whether the effect is active by default.
    pub enabled: bool,
    /// Module-specific parameter overrides.
    pub parameters: std::collections::HashMap<String, f32>,
}

/// A collection of all factory presets, organized by category.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PresetLibrary {
    pub rock_legends: Vec<Preset>,
    pub mj_pop: Vec<Preset>,
    pub celestial: Vec<Preset>,
    pub golden_brass: Vec<Preset>,
    pub obsidian_bass: Vec<Preset>,
    pub synthwave: Vec<Preset>,
    pub vintage_analog: Vec<Preset>,
}


impl Default for PresetLibrary {
    fn default() -> Self {
        Self::new()
    }
}

impl PresetLibrary {
    /// Initializes the library with the full suite of factory presets.
    pub fn new() -> Self {
        Self {
            rock_legends: vec![
                Preset {
                    name: "Back in Black (AC/DC)".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "Exact replica of the iconic Back in Black tone by Malcolm Young. Based on Marshall 1959 Super Lead with Celestion Greenbacks.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.85,
                        pan: 0.50,
                        drive: 0.75,
                        glide: 0.35,
                        attack: 0.70,
                        decay: 0.30,
                        sustain: 0.60,
                        release: 0.40,
                        cutoff: 0.80,
                        res: 0.45,
                        env: 0.65,
                        drive2: 0.55,
                        rev_decay: 0.25,
                        rev_size: 0.40,
                        rev_mix: 0.12,
                        dly_time: 0.20,
                        dly_feed: 0.30,
                        dly_mix: 0.05,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Amplifier".to_string(), enabled: true, parameters: [("gain".to_string(), 0.85), ("presence".to_string(), 0.70)].into_iter().collect() },
                        EffectConfig { name: "Cabinet".to_string(), enabled: true, parameters: [("model".to_string(), 0.0), ("bass".to_string(), 0.75), ("treble".to_string(), 0.80)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Thunderstruck (AC/DC)".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "The unmistakable rhythm guitar sound from Thunderstruck. Tight, punchy rhythm with subtle chorus.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.80,
                        pan: 0.50,
                        drive: 0.65,
                        glide: 0.20,
                        attack: 0.80,
                        decay: 0.25,
                        sustain: 0.50,
                        release: 0.35,
                        cutoff: 0.75,
                        res: 0.40,
                        env: 0.70,
                        drive2: 0.50,
                        rev_decay: 0.30,
                        rev_size: 0.45,
                        rev_mix: 0.15,
                        dly_time: 0.25,
                        dly_feed: 0.35,
                        dly_mix: 0.08,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Amplifier".to_string(), enabled: true, parameters: [("gain".to_string(), 0.75), ("presence".to_string(), 0.65)].into_iter().collect() },
                        EffectConfig { name: "Chorus".to_string(), enabled: true, parameters: [("rate".to_string(), 0.3), ("depth".to_string(), 0.4)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "TNT Growl".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "AC/DC's signature distorted lead tone with aggressive bite and sustain.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.90,
                        pan: 0.50,
                        drive: 0.88,
                        glide: 0.45,
                        attack: 0.60,
                        decay: 0.35,
                        sustain: 0.75,
                        release: 0.45,
                        cutoff: 0.85,
                        res: 0.50,
                        env: 0.75,
                        drive2: 0.60,
                        rev_decay: 0.20,
                        rev_size: 0.35,
                        rev_mix: 0.10,
                        dly_time: 0.18,
                        dly_feed: 0.25,
                        dly_mix: 0.03,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Distortion".to_string(), enabled: true, parameters: [("drive".to_string(), 0.85), ("tone".to_string(), 0.70)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "I Was Made For Lovin' You (KISS)".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "The disco-infused rock anthem tone. Clean rhythm with punchy midrange.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.75,
                        pan: 0.50,
                        drive: 0.45,
                        glide: 0.25,
                        attack: 0.65,
                        decay: 0.40,
                        sustain: 0.40,
                        release: 0.30,
                        cutoff: 0.70,
                        res: 0.55,
                        env: 0.60,
                        drive2: 0.45,
                        rev_decay: 0.35,
                        rev_size: 0.50,
                        rev_mix: 0.18,
                        dly_time: 0.22,
                        dly_feed: 0.40,
                        dly_mix: 0.10,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Amplifier".to_string(), enabled: true, parameters: [("gain".to_string(), 0.55)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Detroit Rock Bass".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "KISS signature heavy bass tone. Deep, punchy with harmonic overtones.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.88,
                        pan: 0.50,
                        drive: 0.60,
                        glide: 0.30,
                        attack: 0.75,
                        decay: 0.35,
                        sustain: 0.55,
                        release: 0.40,
                        cutoff: 0.65,
                        res: 0.40,
                        env: 0.55,
                        drive2: 0.50,
                        rev_decay: 0.25,
                        rev_size: 0.40,
                        rev_mix: 0.12,
                        dly_time: 0.15,
                        dly_feed: 0.20,
                        dly_mix: 0.02,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Overdrive".to_string(), enabled: true, parameters: [("drive".to_string(), 0.55), ("tone".to_string(), 0.65)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "God of Thunder".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "The iconic bass-driven KISS anthem sound. Heavy, distorted with extreme sustain.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.92,
                        pan: 0.50,
                        drive: 0.90,
                        glide: 0.50,
                        attack: 0.50,
                        decay: 0.40,
                        sustain: 0.80,
                        release: 0.50,
                        cutoff: 0.75,
                        res: 0.55,
                        env: 0.70,
                        drive2: 0.65,
                        rev_decay: 0.30,
                        rev_size: 0.45,
                        rev_mix: 0.15,
                        dly_time: 0.20,
                        dly_feed: 0.35,
                        dly_mix: 0.05,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Distortion".to_string(), enabled: true, parameters: [("drive".to_string(), 0.90), ("mode".to_string(), 2.0)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Love Gun Lead".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "Classic KISS lead guitar sound. Crunchy with harmonic richness.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.85,
                        pan: 0.50,
                        drive: 0.78,
                        glide: 0.40,
                        attack: 0.65,
                        decay: 0.35,
                        sustain: 0.65,
                        release: 0.45,
                        cutoff: 0.82,
                        res: 0.48,
                        env: 0.68,
                        drive2: 0.55,
                        rev_decay: 0.28,
                        rev_size: 0.42,
                        rev_mix: 0.14,
                        dly_time: 0.22,
                        dly_feed: 0.32,
                        dly_mix: 0.06,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Smoke on the Water".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "Deep Purple's iconic riff tone. Tight, focused with slight chorus.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.82,
                        pan: 0.50,
                        drive: 0.72,
                        glide: 0.30,
                        attack: 0.75,
                        decay: 0.30,
                        sustain: 0.55,
                        release: 0.38,
                        cutoff: 0.78,
                        res: 0.42,
                        env: 0.62,
                        drive2: 0.52,
                        rev_decay: 0.22,
                        rev_size: 0.38,
                        rev_mix: 0.10,
                        dly_time: 0.18,
                        dly_feed: 0.28,
                        dly_mix: 0.04,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Comfortably Numb".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "Pink Floyd's legendary guitar tone. Smooth, creamy lead with lush reverb.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.78,
                        pan: 0.50,
                        drive: 0.55,
                        glide: 0.35,
                        attack: 0.60,
                        decay: 0.45,
                        sustain: 0.50,
                        release: 0.55,
                        cutoff: 0.70,
                        res: 0.35,
                        env: 0.60,
                        drive2: 0.45,
                        rev_decay: 0.55,
                        rev_size: 0.75,
                        rev_mix: 0.35,
                        dly_time: 0.35,
                        dly_feed: 0.40,
                        dly_mix: 0.15,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Reverb".to_string(), enabled: true, parameters: [("decay".to_string(), 0.60), ("size".to_string(), 0.80)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Sweet Child Lead".to_string(),
                    category: "ROCK LEGENDS".to_string(),
                    description: "Guns N' Roses signature tone. Slight crunch with warm mids.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.85,
                        pan: 0.50,
                        drive: 0.70,
                        glide: 0.35,
                        attack: 0.70,
                        decay: 0.35,
                        sustain: 0.60,
                        release: 0.45,
                        cutoff: 0.75,
                        res: 0.45,
                        env: 0.65,
                        drive2: 0.50,
                        rev_decay: 0.32,
                        rev_size: 0.48,
                        rev_mix: 0.18,
                        dly_time: 0.28,
                        dly_feed: 0.35,
                        dly_mix: 0.08,
                    },
                    effects_chain: vec![],
                },
            ],
            mj_pop: vec![
                Preset {
                    name: "Billie Jean Bass".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "The iconic Billie Jean bass line sound. Tight, punchy with slight compression.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.80,
                        pan: 0.50,
                        drive: 0.40,
                        glide: 0.15,
                        attack: 0.85,
                        decay: 0.25,
                        sustain: 0.35,
                        release: 0.25,
                        cutoff: 0.60,
                        res: 0.35,
                        env: 0.50,
                        drive2: 0.40,
                        rev_decay: 0.20,
                        rev_size: 0.35,
                        rev_mix: 0.08,
                        dly_time: 0.12,
                        dly_feed: 0.15,
                        dly_mix: 0.02,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Compressor".to_string(), enabled: true, parameters: [("threshold".to_string(), -15.0), ("ratio".to_string(), 4.0)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Thriller Growl".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Thriller's bass growl. Deep, menacing with punchy attack.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.82,
                        pan: 0.50,
                        drive: 0.55,
                        glide: 0.25,
                        attack: 0.80,
                        decay: 0.30,
                        sustain: 0.45,
                        release: 0.35,
                        cutoff: 0.55,
                        res: 0.40,
                        env: 0.55,
                        drive2: 0.45,
                        rev_decay: 0.25,
                        rev_size: 0.40,
                        rev_mix: 0.10,
                        dly_time: 0.15,
                        dly_feed: 0.20,
                        dly_mix: 0.03,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Compressor".to_string(), enabled: true, parameters: [("threshold".to_string(), -12.0), ("ratio".to_string(), 6.0)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Beat It Synth".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Eddie Van Halen's legendary solo sound. Creamy, singing lead.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.88,
                        pan: 0.50,
                        drive: 0.65,
                        glide: 0.30,
                        attack: 0.70,
                        decay: 0.35,
                        sustain: 0.70,
                        release: 0.50,
                        cutoff: 0.85,
                        res: 0.50,
                        env: 0.75,
                        drive2: 0.60,
                        rev_decay: 0.35,
                        rev_size: 0.55,
                        rev_mix: 0.20,
                        dly_time: 0.30,
                        dly_feed: 0.45,
                        dly_mix: 0.12,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Delay".to_string(), enabled: true, parameters: [("time".to_string(), 0.28), ("feedback".to_string(), 0.40)].into_iter().collect() },
                        EffectConfig { name: "Reverb".to_string(), enabled: true, parameters: [("decay".to_string(), 0.40), ("mix".to_string(), 0.25)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Smooth Criminal".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Smooth Criminal's bass. Punchy, synth-like with tight attack.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.85,
                        pan: 0.50,
                        drive: 0.50,
                        glide: 0.20,
                        attack: 0.85,
                        decay: 0.20,
                        sustain: 0.40,
                        release: 0.30,
                        cutoff: 0.65,
                        res: 0.42,
                        env: 0.58,
                        drive2: 0.48,
                        rev_decay: 0.22,
                        rev_size: 0.38,
                        rev_mix: 0.10,
                        dly_time: 0.14,
                        dly_feed: 0.18,
                        dly_mix: 0.03,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Man In Mirror".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Powerful, soaring lead tone with lush reverb.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.82,
                        pan: 0.50,
                        drive: 0.60,
                        glide: 0.35,
                        attack: 0.65,
                        decay: 0.40,
                        sustain: 0.55,
                        release: 0.50,
                        cutoff: 0.75,
                        res: 0.40,
                        env: 0.62,
                        drive2: 0.50,
                        rev_decay: 0.50,
                        rev_size: 0.70,
                        rev_mix: 0.30,
                        dly_time: 0.32,
                        dly_feed: 0.38,
                        dly_mix: 0.10,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Reverb".to_string(), enabled: true, parameters: [("decay".to_string(), 0.55), ("size".to_string(), 0.75)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "P.Y.T. Pulse".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Upbeat, punchy synth bass from P.Y.T.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.80,
                        pan: 0.50,
                        drive: 0.45,
                        glide: 0.15,
                        attack: 0.80,
                        decay: 0.22,
                        sustain: 0.35,
                        release: 0.28,
                        cutoff: 0.68,
                        res: 0.45,
                        env: 0.55,
                        drive2: 0.45,
                        rev_decay: 0.18,
                        rev_size: 0.32,
                        rev_mix: 0.06,
                        dly_time: 0.10,
                        dly_feed: 0.12,
                        dly_mix: 0.02,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Don't Stop Pop".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Feel Alive rhythm guitar. Bright, punchy pop tone.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.78,
                        pan: 0.50,
                        drive: 0.50,
                        glide: 0.20,
                        attack: 0.75,
                        decay: 0.30,
                        sustain: 0.40,
                        release: 0.35,
                        cutoff: 0.80,
                        res: 0.40,
                        env: 0.65,
                        drive2: 0.50,
                        rev_decay: 0.25,
                        rev_size: 0.42,
                        rev_mix: 0.12,
                        dly_time: 0.18,
                        dly_feed: 0.25,
                        dly_mix: 0.05,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Dirty Diana Lead".to_string(),
                    category: "MJ POP ANTHOLOGY".to_string(),
                    description: "Aggressive, overdriven lead with attitude.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.88,
                        pan: 0.50,
                        drive: 0.80,
                        glide: 0.40,
                        attack: 0.60,
                        decay: 0.32,
                        sustain: 0.70,
                        release: 0.42,
                        cutoff: 0.82,
                        res: 0.52,
                        env: 0.72,
                        drive2: 0.58,
                        rev_decay: 0.28,
                        rev_size: 0.45,
                        rev_mix: 0.15,
                        dly_time: 0.24,
                        dly_feed: 0.32,
                        dly_mix: 0.06,
                    },
                    effects_chain: vec![],
                },
            ],
            celestial: vec![
                Preset {
                    name: "Archangel Pad".to_string(),
                    category: "CELESTIAL CHOIRS".to_string(),
                    description: "Lush, ethereal pad with heavenly shimmer.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.70,
                        pan: 0.50,
                        drive: 0.20,
                        glide: 0.40,
                        attack: 0.50,
                        decay: 0.60,
                        sustain: 0.70,
                        release: 0.80,
                        cutoff: 0.65,
                        res: 0.30,
                        env: 0.55,
                        drive2: 0.35,
                        rev_decay: 0.80,
                        rev_size: 0.90,
                        rev_mix: 0.45,
                        dly_time: 0.40,
                        dly_feed: 0.30,
                        dly_mix: 0.08,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Reverb".to_string(), enabled: true, parameters: [("decay".to_string(), 0.85), ("size".to_string(), 0.95)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Seraphim Vox".to_string(),
                    category: "CELESTIAL CHOIRS".to_string(),
                    description: "Angelic vocal synth with crystalline highs.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.72,
                        pan: 0.50,
                        drive: 0.25,
                        glide: 0.35,
                        attack: 0.45,
                        decay: 0.55,
                        sustain: 0.65,
                        release: 0.75,
                        cutoff: 0.75,
                        res: 0.35,
                        env: 0.60,
                        drive2: 0.40,
                        rev_decay: 0.75,
                        rev_size: 0.88,
                        rev_mix: 0.42,
                        dly_time: 0.35,
                        dly_feed: 0.28,
                        dly_mix: 0.06,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Divine Breath".to_string(),
                    category: "CELESTIAL CHOIRS".to_string(),
                    description: "Breathing, evolving ambient texture.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.65,
                        pan: 0.50,
                        drive: 0.15,
                        glide: 0.50,
                        attack: 0.60,
                        decay: 0.70,
                        sustain: 0.75,
                        release: 0.90,
                        cutoff: 0.60,
                        res: 0.25,
                        env: 0.50,
                        drive2: 0.30,
                        rev_decay: 0.90,
                        rev_size: 0.95,
                        rev_mix: 0.50,
                        dly_time: 0.50,
                        dly_feed: 0.35,
                        dly_mix: 0.10,
                    },
                    effects_chain: vec![],
                },
            ],
            golden_brass: vec![
                Preset {
                    name: "Trumpet of Zion".to_string(),
                    category: "GOLDEN BRASS".to_string(),
                    description: "Bold, brass-forward tone with punch.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.82,
                        pan: 0.50,
                        drive: 0.55,
                        glide: 0.25,
                        attack: 0.75,
                        decay: 0.30,
                        sustain: 0.50,
                        release: 0.40,
                        cutoff: 0.80,
                        res: 0.45,
                        env: 0.70,
                        drive2: 0.55,
                        rev_decay: 0.35,
                        rev_size: 0.55,
                        rev_mix: 0.20,
                        dly_time: 0.25,
                        dly_feed: 0.30,
                        dly_mix: 0.05,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Throne Room".to_string(),
                    category: "GOLDEN BRASS".to_string(),
                    description: "Majestic, orchestral brass ensemble.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.80,
                        pan: 0.50,
                        drive: 0.45,
                        glide: 0.30,
                        attack: 0.65,
                        decay: 0.40,
                        sustain: 0.55,
                        release: 0.50,
                        cutoff: 0.75,
                        res: 0.40,
                        env: 0.62,
                        drive2: 0.48,
                        rev_decay: 0.50,
                        rev_size: 0.75,
                        rev_mix: 0.30,
                        dly_time: 0.35,
                        dly_feed: 0.35,
                        dly_mix: 0.08,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Reverb".to_string(), enabled: true, parameters: [("decay".to_string(), 0.55), ("size".to_string(), 0.80)].into_iter().collect() },
                    ],
                },
            ],
            obsidian_bass: vec![
                Preset {
                    name: "Deep Resonance".to_string(),
                    category: "OBSIDIAN BASS".to_string(),
                    description: "Sub-frequency bass with harmonic depth.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.85,
                        pan: 0.50,
                        drive: 0.50,
                        glide: 0.20,
                        attack: 0.80,
                        decay: 0.28,
                        sustain: 0.45,
                        release: 0.35,
                        cutoff: 0.50,
                        res: 0.35,
                        env: 0.48,
                        drive2: 0.42,
                        rev_decay: 0.22,
                        rev_size: 0.40,
                        rev_mix: 0.08,
                        dly_time: 0.12,
                        dly_feed: 0.15,
                        dly_mix: 0.02,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Earth Pillar".to_string(),
                    category: "OBSIDIAN BASS".to_string(),
                    description: "Solid, grounding bass with authority.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.88,
                        pan: 0.50,
                        drive: 0.55,
                        glide: 0.25,
                        attack: 0.82,
                        decay: 0.30,
                        sustain: 0.48,
                        release: 0.38,
                        cutoff: 0.55,
                        res: 0.38,
                        env: 0.50,
                        drive2: 0.45,
                        rev_decay: 0.25,
                        rev_size: 0.45,
                        rev_mix: 0.10,
                        dly_time: 0.14,
                        dly_feed: 0.18,
                        dly_mix: 0.02,
                    },
                    effects_chain: vec![],
                },
            ],
            synthwave: vec![
                Preset {
                    name: "Neon Nights".to_string(),
                    category: "SYNTHWAVE 84".to_string(),
                    description: "Retro synthwave rhythm with clean punch.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.78,
                        pan: 0.50,
                        drive: 0.35,
                        glide: 0.20,
                        attack: 0.75,
                        decay: 0.25,
                        sustain: 0.40,
                        release: 0.30,
                        cutoff: 0.75,
                        res: 0.45,
                        env: 0.60,
                        drive2: 0.50,
                        rev_decay: 0.30,
                        rev_size: 0.50,
                        rev_mix: 0.20,
                        dly_time: 0.35,
                        dly_feed: 0.45,
                        dly_mix: 0.15,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Delay".to_string(), enabled: true, parameters: [("time".to_string(), 0.35), ("feedback".to_string(), 0.50)].into_iter().collect() },
                        EffectConfig { name: "Reverb".to_string(), enabled: true, parameters: [("decay".to_string(), 0.35)].into_iter().collect() },
                    ],
                },
                Preset {
                    name: "Outrun Lead".to_string(),
                    category: "SYNTHWAVE 84".to_string(),
                    description: "Classic 80s lead synth with portamento.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.82,
                        pan: 0.50,
                        drive: 0.45,
                        glide: 0.45,
                        attack: 0.65,
                        decay: 0.35,
                        sustain: 0.55,
                        release: 0.45,
                        cutoff: 0.82,
                        res: 0.50,
                        env: 0.65,
                        drive2: 0.55,
                        rev_decay: 0.35,
                        rev_size: 0.55,
                        rev_mix: 0.22,
                        dly_time: 0.40,
                        dly_feed: 0.50,
                        dly_mix: 0.18,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Vapor Keys".to_string(),
                    category: "SYNTHWAVE 84".to_string(),
                    description: "Dreamy, phased keys with warmth.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.75,
                        pan: 0.50,
                        drive: 0.30,
                        glide: 0.30,
                        attack: 0.60,
                        decay: 0.40,
                        sustain: 0.50,
                        release: 0.50,
                        cutoff: 0.70,
                        res: 0.40,
                        env: 0.58,
                        drive2: 0.45,
                        rev_decay: 0.40,
                        rev_size: 0.60,
                        rev_mix: 0.25,
                        dly_time: 0.30,
                        dly_feed: 0.40,
                        dly_mix: 0.12,
                    },
                    effects_chain: vec![
                        EffectConfig { name: "Phaser".to_string(), enabled: true, parameters: [("rate".to_string(), 0.5), ("depth".to_string(), 0.6)].into_iter().collect() },
                    ],
                },
            ],
            vintage_analog: vec![
                Preset {
                    name: "Jupiter 8 Lead".to_string(),
                    category: "VINTAGE ANALOG".to_string(),
                    description: "Roland Jupiter-8 emulation. Rich, warm analog.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.80,
                        pan: 0.50,
                        drive: 0.40,
                        glide: 0.35,
                        attack: 0.60,
                        decay: 0.40,
                        sustain: 0.55,
                        release: 0.50,
                        cutoff: 0.75,
                        res: 0.45,
                        env: 0.60,
                        drive2: 0.50,
                        rev_decay: 0.30,
                        rev_size: 0.50,
                        rev_mix: 0.18,
                        dly_time: 0.28,
                        dly_feed: 0.35,
                        dly_mix: 0.08,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "Prophet Strings".to_string(),
                    category: "VINTAGE ANALOG".to_string(),
                    description: "Sequential Prophet-5 style strings.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.75,
                        pan: 0.50,
                        drive: 0.30,
                        glide: 0.25,
                        attack: 0.55,
                        decay: 0.50,
                        sustain: 0.60,
                        release: 0.65,
                        cutoff: 0.70,
                        res: 0.35,
                        env: 0.55,
                        drive2: 0.42,
                        rev_decay: 0.45,
                        rev_size: 0.70,
                        rev_mix: 0.28,
                        dly_time: 0.32,
                        dly_feed: 0.30,
                        dly_mix: 0.06,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "MiniMoog Bass".to_string(),
                    category: "VINTAGE ANALOG".to_string(),
                    description: "Classic Moog bass. Fat, punchy, legendary.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.85,
                        pan: 0.50,
                        drive: 0.50,
                        glide: 0.20,
                        attack: 0.80,
                        decay: 0.25,
                        sustain: 0.40,
                        release: 0.35,
                        cutoff: 0.60,
                        res: 0.50,
                        env: 0.55,
                        drive2: 0.45,
                        rev_decay: 0.20,
                        rev_size: 0.35,
                        rev_mix: 0.08,
                        dly_time: 0.10,
                        dly_feed: 0.12,
                        dly_mix: 0.02,
                    },
                    effects_chain: vec![],
                },
                Preset {
                    name: "TB-303 Acid".to_string(),
                    category: "VINTAGE ANALOG".to_string(),
                    description: "Roland TB-303 squelch. Iconic acid bass.".to_string(),
                    parameters: PresetParameters {
                        volume: 0.82,
                        pan: 0.50,
                        drive: 0.70,
                        glide: 0.15,
                        attack: 0.85,
                        decay: 0.20,
                        sustain: 0.30,
                        release: 0.25,
                        cutoff: 0.65,
                        res: 0.75,
                        env: 0.70,
                        drive2: 0.55,
                        rev_decay: 0.15,
                        rev_size: 0.30,
                        rev_mix: 0.05,
                        dly_time: 0.08,
                        dly_feed: 0.10,
                        dly_mix: 0.01,
                    },
                    effects_chain: vec![],
                },
            ],
        }
    }

    /// Returns a flat list of references to all presets in the library.
    pub fn all_presets(&self) -> Vec<&Preset> {
        let mut all = Vec::new();
        all.extend(&self.rock_legends);
        all.extend(&self.mj_pop);
        all.extend(&self.celestial);
        all.extend(&self.golden_brass);
        all.extend(&self.obsidian_bass);
        all.extend(&self.synthwave);
        all.extend(&self.vintage_analog);
        all
    }

    /// Searches for a preset by its exact name.
    pub fn get_by_name(&self, name: &str) -> Option<&Preset> {
        self.all_presets().into_iter().find(|p| p.name == name)
    }

    /// Returns all presets belonging to a specific category.
    pub fn get_by_category(&self, category: &str) -> Vec<&Preset> {
        match category {
            "ROCK LEGENDS" => self.rock_legends.iter().collect(),
            "MJ POP ANTHOLOGY" => self.mj_pop.iter().collect(),
            "CELESTIAL CHOIRS" => self.celestial.iter().collect(),
            "GOLDEN BRASS" => self.golden_brass.iter().collect(),
            "OBSIDIAN BASS" => self.obsidian_bass.iter().collect(),
            "SYNTHWAVE 84" => self.synthwave.iter().collect(),
            "VINTAGE ANALOG" => self.vintage_analog.iter().collect(),
            _ => Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_preset_library_loading() {
        let library = PresetLibrary::new();
        assert!(!library.rock_legends.is_empty());
        assert!(!library.mj_pop.is_empty());
        
        // Check a specific preset
        let acdc = &library.rock_legends[0];
        assert_eq!(acdc.name, "Back in Black (AC/DC)");
        assert!(acdc.parameters.drive > 0.0);
    }
}
