[package]
name = "smoothie-ai-distributed"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
libp2p = { version = "0.53", features = ["gossipsub", "mdns", "tcp", "noise", "yamux"] }
smoothie-ai = { workspace = true }
anyhow.workspace = true
tokio.workspace = true
