[package]
name = "smoothie-arrangement"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
smoothie-core = { workspace = true }
smoothie-ai = { workspace = true }
serde = {workspace = true, features = ["derive"]}
anyhow.workspace = true
