[package]
name = "smoothie-arrangement"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "A Seraphic Technologies Elite audio plugin framework crate."
repository = "https://github.com/seraphic/smoothie-elite"

[dependencies]
smoothie-core = { workspace = true }
smoothie-ai = { workspace = true }
serde = {workspace = true, features = ["derive"]}
anyhow.workspace = true
