/*
 *  S E R A P H I C   T E C H N O L O G I E S
 * ╭──────────────────────────────────────────────────────────────────────────╮
 * │ FILE ID: SER-0x9080ff78 | REVISION: 2026.04.20                           │
 * │ PATH: smoothie_elite/crates/03-cognition/smoothie-graph/src/nodes/mod.rs                                                         │
 * ├──────────────────────────────────────────────────────────────────────────┤
 * │ DESCRIPTION: Professional technical implementation and documentation.    │
 * ├──────────────────────────────────────────────────────────────────────────┤
 * │ TECHNICAL NOTES: Optimized for industrial-grade performance standards.   │
 * ╰──────────────────────────────────────────────────────────────────────────╯
 *   SERAPHIC TECH - Precision Engineering
 */

use smoothie_core::math::FloatExt;
use smoothie_core::primitives::Sample;

/// An opaque, copy-able node identifier generated by the graph registry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
/// Technical implementation of the NodeId structure.
pub struct NodeId(pub u32);

/// Technical implementation of the NodeConfig structure.
pub struct NodeConfig {
    pub sample_rate: f32,
    pub block_size: usize,
    pub channel_count: usize,
}

///
///
/// - `process()` allocates **zero** bytes on the heap.
/// - `process()` does not perform I/O, logging, or panicking.
pub trait AudioNode: Send {
    /// Human-readable name for debugging and UI display.
    fn name(&self) -> &'static str;

    /// Initialise the node with the host session configuration.
    fn init(&mut self, config: &NodeConfig);

    /// Reset all internal state (phase, history, envelopes) to zero.
    fn reset(&mut self);

    /// Process a single block of audio.
    ///
    /// - `inputs`  — slice of interleaved channel buffers feeding this node.
    /// - `outputs` — slice of interleaved channel buffers produced by this node.
    fn process(&mut self, inputs: &[&[Sample]], outputs: &mut [&mut [Sample]]);

    /// Number of audio input channels this node expects.
    fn input_channel_count(&self) -> usize {
        0
    }

    /// Number of audio output channels this node produces.
    fn output_channel_count(&self) -> usize {
        2
    }
}

// ─────────────────────────────────────────────────────────────
//  Concrete built-in nodes
// ─────────────────────────────────────────────────────────────

/// Technical implementation of the PassThroughNode structure.
pub struct PassThroughNode {
    gain: f32,
}

impl PassThroughNode {
    /// Initializes a new instance of the associated type.
    pub fn new(gain: f32) -> Self {
        Self { gain }
    }
}

impl AudioNode for PassThroughNode {
    /// Technical implementation of the name logic.
    fn name(&self) -> &'static str {
        "PassThrough"
    }
    /// Technical implementation of the init logic.
    fn init(&mut self, _config: &NodeConfig) {}
    /// Resets the internal state of the component.
    fn reset(&mut self) {}
    /// Technical implementation of the input_channel_count logic.
    fn input_channel_count(&self) -> usize {
        2
    }
    /// Technical implementation of the output_channel_count logic.
    fn output_channel_count(&self) -> usize {
        2
    }

    /// Primary real-time signal processing execution block.
    fn process(&mut self, inputs: &[&[Sample]], outputs: &mut [&mut [Sample]]) {
        for (in_ch, out_ch) in inputs.iter().zip(outputs.iter_mut()) {
            for (i, o) in in_ch.iter().zip(out_ch.iter_mut()) {
                *o = *i * self.gain;
            }
        }
    }
}

/// Technical implementation of the StereoBusNode structure.
pub struct StereoBusNode {
    gain_l: f32,
    gain_r: f32,
}

impl StereoBusNode {
    /// Initializes a new instance of the associated type.
    pub fn new() -> Self {
        Self {
            gain_l: 1.0,
            gain_r: 1.0,
        }
    }

    /// Technical implementation of the set_pan logic.
    pub fn set_pan(&mut self, pan: f32) {
        // Constant-power panning law: cos/sin approximation
        let pan = pan.clamp(-1.0, 1.0);
        let angle = (pan + 1.0) * 0.25; // [0.0 .. 0.5] of the unit circle
        let cos_val = smoothie_core::math::sine_approx(angle + 0.25);
        let sin_val = smoothie_core::math::sine_approx(angle);
        self.gain_l = cos_val;
        self.gain_r = sin_val;
    }
}

impl AudioNode for StereoBusNode {
    /// Technical implementation of the name logic.
    fn name(&self) -> &'static str {
        "StereoBus"
    }
    /// Technical implementation of the init logic.
    fn init(&mut self, _config: &NodeConfig) {}
    /// Resets the internal state of the component.
    fn reset(&mut self) {}
    /// Technical implementation of the input_channel_count logic.
    fn input_channel_count(&self) -> usize {
        2
    }
    /// Technical implementation of the output_channel_count logic.
    fn output_channel_count(&self) -> usize {
        2
    }

    /// Primary real-time signal processing execution block.
    fn process(&mut self, inputs: &[&[Sample]], outputs: &mut [&mut [Sample]]) {
        if inputs.len() >= 2 && outputs.len() >= 2 {
            let (il, ir) = (&inputs[0], &inputs[1]);
            let (ol, or_) = outputs.split_at_mut(1);
            for i in 0..ol[0].len() {
                ol[0][i] = il[i] * self.gain_l;
                or_[0][i] = ir[i] * self.gain_r;
            }
        }
    }
}

///
/// Technical implementation of the DcBlocker structure.
pub struct DcBlocker {
    x_prev: [f32; 2],
    y_prev: [f32; 2],
    r: f32,
}

impl DcBlocker {
    /// `r` should be close to 1.0 (e.g. 0.9975) for very low cutoff.
    pub fn new(r: f32) -> Self {
        Self {
            x_prev: [0.0; 2],
            y_prev: [0.0; 2],
            r,
        }
    }
}

impl AudioNode for DcBlocker {
    /// Technical implementation of the name logic.
    fn name(&self) -> &'static str {
        "DcBlocker"
    }
    /// Technical implementation of the init logic.
    fn init(&mut self, _config: &NodeConfig) {}
    /// Resets the internal state of the component.
    fn reset(&mut self) {
        self.x_prev = [0.0; 2];
        self.y_prev = [0.0; 2];
    }
    /// Technical implementation of the input_channel_count logic.
    fn input_channel_count(&self) -> usize {
        2
    }
    /// Technical implementation of the output_channel_count logic.
    fn output_channel_count(&self) -> usize {
        2
    }

    /// Primary real-time signal processing execution block.
    fn process(&mut self, inputs: &[&[Sample]], outputs: &mut [&mut [Sample]]) {
        for ch in 0..2.min(inputs.len()).min(outputs.len()) {
            for (x, y) in inputs[ch].iter().zip(outputs[ch].iter_mut()) {
                let y_val = *x - self.x_prev[ch] + self.r * self.y_prev[ch];
                self.x_prev[ch] = *x;
                self.y_prev[ch] = y_val;
                *y = y_val;
            }
        }
    }
}
