#
#   S E R A P H I C   T E C H N O L O G I E S
#  ────────────────────────────────────────────────────────────────────────────
#   FILE ID: SER-0x8ee57ac4 | REVISION: 2026.04.20
#   PATH: smoothie_elite/crates/02-resonance/synth/Cargo.toml
#  ────────────────────────────────────────────────────────────────────────────
#   SERAPHIC TECH - Precision Engineering
#

[package]
name = "smoothie-synth"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "A Seraphic Technologies Elite audio plugin framework crate."
repository = "https://github.com/seraphic/smoothie-elite"

[dependencies]
smoothie-midi = { workspace = true }
smoothie-core = { workspace = true }
smoothie-dsp = { workspace = true }
smoothie-ironstack = { workspace = true }
seraphic-multiverse = { path = "../../03-cognition/seraphic-multiverse" , version = "1.0.0"}

[lib]
path = "src/lib.rs"
