#
#   S E R A P H I C   T E C H N O L O G I E S
#  ────────────────────────────────────────────────────────────────────────────
#   FILE ID: SER-0x8ee57ac4 | REVISION: 2026.04.20
#   PATH: smoothie_elite/crates/02-resonance/synth/Cargo.toml
#  ────────────────────────────────────────────────────────────────────────────
#   SERAPHIC TECH - Precision Engineering
#

[package]
name = "smoothie-synth"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
smoothie-midi = { workspace = true }
smoothie-core = { workspace = true }
smoothie-dsp = { workspace = true }
smoothie-ironstack = { workspace = true }
seraphic-multiverse = { workspace = true }

[lib]
path = "src/lib.rs"
