#
#   S E R A P H I C   T E C H N O L O G I E S
#  ────────────────────────────────────────────────────────────────────────────
#   FILE ID: SER-0xb0144154 | REVISION: 2026.04.20
#   PATH: crates/04-holography/smoothie-ui-render/Cargo.toml
#  ────────────────────────────────────────────────────────────────────────────
#   SERAPHIC TECH - Precision Engineering
#

[package]
name = "smoothie-ui-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
smoothie-core = {workspace = true}
smoothie-ui-core = {workspace = true}
smoothie-math = {workspace = true}
anyhow = {workspace = true}
log = {workspace = true}
bytemuck = {workspace = true}

[dev-dependencies]
tokio = {workspace = true}
