[package]
name        = "smoothie-vst3"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "smoothie-vst3 — Smoothie Elite audio plugin framework"

[dependencies]
log             = { workspace = true }
serde           = { workspace = true }
smoothie-core   = { workspace = true }
smoothie-params = { workspace = true }
vst3-sys        = { workspace = true }
parking_lot     = { workspace = true }
atomic_float    = { workspace = true }
